edition: 1.0.0 #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: fc-sdtest
access: default
vars:
  region: "cn-hangzhou" 
  serviceName: "serverless-sdtest"
  functionName: "sdtest" 
  filemgrFilename: "filemgr-1.2.2"
  # imageUrl: "registry.cn-hangzhou.aliyuncs.com/aliyun-fc/fc-stable-diffusion:anime-v12" 
  imageUrl: "registry.cn-hangzhou.aliyuncs.com/pdkpdk/sdcpprelease:1"
  enableCollect: ""
  service:
    name: "serverless-sdtest"
    description: 'sdtest 部署到函数计算'
    internetAccess: true
    nasConfig: auto

services:
  sdtest:
    component: fc
    actions: 
      post-deploy: 
        - component: fc ondemand put --qualifier LATEST --max 1
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: ${vars.functionName}
        description: sdtest函数
        handler: index.handler
        timeout: 600
        diskSize: 10240
        caPort: 36000
        instanceType: fc.gpu.tesla.1
        runtime: custom-container
        cpu: 8
        customContainerConfig:
          args: ''
          accelerationType: Default
          image: ${vars.imageUrl}
          accelerationInfo:
            status: Preparing
          command: ''
          webServerMode: true
        instanceConcurrency: 100
        memorySize: 32768
        gpuMemorySize: 16384
        asyncConfiguration: {}
        environmentVariables:
          EXTRA_ARGS: ${vars.extraArgs}
          ENABLE_COLLECT: ${vars.enableCollect}
      triggers:
        - name: defaultTrigger
          description: ''
          type: http
          qualifier: LATEST
          config:
            methods:
              - GET
              - POST
              - PUT
              - DELETE
            authType: anonymous
            disableURLInternet: false
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*

  filemgr:
    component: fc 
    actions: 
      pre-deploy:
         - run: |
            mkdir -p src/code && cd src/code && \
            curl http://serverless-tool-images.oss-cn-hangzhou.aliyuncs.com/aigc/filemgr/${vars.filemgrFilename}.zip -o filemgr.zip && \
            unzip filemgr.zip && \
            mv dist/ filemgr/
           path: ./
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: "admin"
        description: '模型管理辅助工具'
        codeUri: './src/code/filemgr'
        runtime: custom
        timeout: 7200
        memorySize: 3072
        cpu: 2.0
        diskSize: 512
        instanceConcurrency: 16
        caPort: 9000
        customRuntimeConfig:
          command:
            - ./server
        environmentVariables:
          TOKEN: ${vars.filemgrToken}
          ENABLE_COLLECT: ${vars.enableCollect}
          SD_VERSION: ""
          SD_FUNCTION_NAME: "sdtest"
          SD_DOMAIN: ""
        layers:
          - "acs:fc:${vars.region}:official:layers/ServerlessDevs/versions/1"
          - "acs:fc:${vars.region}:official:layers/Python310/versions/2"
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
